# Generated by Django 2.2.7 on 2019-11-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webelopers', '0002_auto_20191108_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
